[workspace]

members = [
    "atelier-assembler",
    "atelier-core",
    "atelier-describe",
    "atelier-json",
    "atelier-lib",
    "atelier-openapi",
    "atelier-query",
    "atelier-rdf",
    "atelier-smithy",
    "atelier-test",
    "cargo-atelier",
    "sufy-json2smithy"
    ]
